spring.application.name=libreria-api

spring.datasource.url=jdbc:mysql://localhost:3306/libreria
spring.datasource.username=AngelDB
spring.datasource.password=######
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
